image:
  repository: liferay/dxp
  tag: "2025.q3.9"
  pullPolicy: IfNotPresent

resources: {}
replicaCount: 1

service:
  port: 8080
  debugPort: 11311

elasticsearch:
  host: "search-elastic-es-http:9200"
  username: "elastic"
  password: "MyFixedPassword123!"

java:
  version: "21"
  jvmOpts: "-Xms4g -Xmx4g"

database:
  host: db-mariadb
  port: 3306
  database: lportal
  username: root
  password: root

mailhog:
  host: mailhog-server
  smtpPort: 1025
  pop3Port: 8025

ingress:
  enabled: true
  className: "nginx"
  host: "liferay.localhost"
