apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailhog.fullname" . }}
  labels:
    app: {{ include "mailhog.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: {{ .Values.service.smtpPort }}
      targetPort: smtp
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
  selector:
    app: {{ include "mailhog.name" . }}
