enabled: false

image:
  repository: "ghcr.io/cloudnative-pg/postgresql"
  tag: "17"
  pullPolicy: IfNotPresent

rootPassword:
  simple:
    enabled: false
    username: "postgres"
    password: "postgres"

database: lportal

storage:
