{{- if or .Values.elasticsearch.enabled .Values.documentlibrary.local  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liferay-dxp.fullname" . }}-osgi-configs
data:
  {{- if .Values.elasticsearch.enabled }}
  com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config: |
    networkHostAddresses=["{{ .Release.Name }}-{{ .Values.elasticsearch.host }}"]
    operationMode="REMOTE"
    authenticationEnabled=B"true"
    username="{{ .Values.elasticsearch.username }}"
    password="{{ .Values.elasticsearch.password }}"
  {{- end }}
  {{- if .Values.documentlibrary.local }}
  com.liferay.portal.store.file.system.configuration.AdvancedFileSystemStoreConfiguration.config: |
    rootDir="data/document_library"
  {{- end }}
{{- end }}
