apiVersion: v1
kind: Service
metadata:
  name: {{ include "liferay-dxp.fullname" . }}
  labels:
    app: {{ include "liferay-dxp.name" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.webPort }}
      targetPort: 8080
    {{- if .Values.gogo.enabled }}
    - name: gogo
      port: {{ .Values.gogo.port }}
      targetPort: 11311
    {{- end }}
  selector:
    app: {{ include "liferay-dxp.name" . }}
