apiVersion: v1
kind: Service
metadata:
  name: {{ include "liferay-dxp.fullname" . }}
  labels:
    app: {{ include "liferay-dxp.name" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: debug
      port: {{ .Values.service.debugPort }}
      targetPort: {{ .Values.service.debugPort }}
  selector:
    app: {{ include "liferay-dxp.name" . }}
