apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "liferay-dxp.fullname" . }}
spec:
  serviceName: {{ include "liferay-dxp.fullname" . }}
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "liferay-dxp.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "liferay-dxp.name" . }}

    spec:
      containers:
        - name: liferay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
{{- if .Values.mail.enabled }}
            # --- Mail
            - name: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_HOST
              value: "{{ .Release.Name }}-{{ .Values.mail.host }}"
            - name: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_PORT
              value: "{{ .Values.mail.smtpPort }}"
{{- end }}

            # --- Java version (optional)
            - name: JAVA_VERSION
              value: "zulu{{ .Values.java.version }}"

            # --- JVM opts
            - name: LIFERAY_JVM_OPTS
              value: "{{ .Values.java.jvmOpts }}"

            {{- $params := list -}}
            {{- range .Values.database.urlParams }}
              {{- $params = append $params (printf "%s=%s" .key .value) }}
            {{- end }}

            # --- DB
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME
              value: "{{ .Values.database.driver }}"
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
              value: "jdbc:{{ .Values.database.type }}://{{ .Release.Name }}-{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.database }}{{- if .Values.database.urlParams }}?{{- end }}{{ join "&" $params }}"
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
              value: "{{ .Values.database.username }}"
            - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
              value: "{{ .Values.database.password }}"

            # --- Misc Liferay
            - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
              value: "0.0.0.0:{{ .Values.gogo.port }}"

            # --- Retry JDBC on startup
            - name: LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY
              value: "20"
            - name: LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES
              value: "10"

            # --- Liferay behavior flags
            {{- range $key, $value := .Values.liferayFlags }}
            - name: LIFERAY_{{ $key }}
              value: "{{ $value }}"
            {{- end }}

            # --- Protocol & server URL
            - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_PROTOCOL
              value: "http"
            - name: SERVER_URL
              value: "http://{{ .Values.ingress.host }}"

            # --- Valid virtual hosts
            - name: LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS
              value: "localhost,127.0.0.1,{{ .Values.ingress.host }},{{ include "liferay-dxp.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local,*.svc.cluster.local,10.0.0.0/8"

          ports:
            - name: http
              containerPort: 8080
            {{- if .Values.gogo.enabled }}
            - name: gogo
              containerPort: 11311
            {{- end }}

          volumeMounts:
            {{- if or .Values.elasticsearch.enabled .Values.documentlibrary.local  }}
            - name: osgi-configs
              mountPath: /mnt/liferay/files/osgi/configs
            {{- end }}
            {{- if or .Values.logouttimer.enabled .Values.remotedebugging.enabled  }}
            - name: scripts
              mountPath: /mnt/liferay/scripts
            {{- end }}

      volumes:
        {{- if or .Values.elasticsearch.enabled .Values.documentlibrary.local  }}
        - name: osgi-configs
          configMap:
            name: {{ include "liferay-dxp.fullname" . }}-osgi-configs
        {{- end }}
        {{- if or .Values.logouttimer.enabled .Values.remotedebugging.enabled  }}
        - name: scripts
          configMap:
            name: {{ include "liferay-dxp.fullname" . }}-scripts
        {{- end }}
