enabled: false

image:
  pullPolicy: IfNotPresent
  version: "8.19.7"

plugins:
  - analysis-icu
  - analysis-kuromoji
  - analysis-smartcn
  - analysis-stempel

certificates:
  enabled: true

password:
  simple:
    enabled: false
    password: "MyFixedPassword123!"

ingress:
  enabled: false
  host: "elasticsearch.localhost"
  className: "nginx"
