{{- if and .Values.enabled .Values.rootPassword.simple.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-mariadb.fullname" . }}-root
type: Opaque
stringData:
  password: {{ .Values.rootPassword.simple.password | quote }}
{{- end }}