{{- if .Values.enabled  }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{.Values.database }}
spec:
  mariaDbRef:
    name: {{ include "db-mariadb.fullname" . }}
  characterSet: utf8
  collate: utf8_general_ci
{{- end }}