{{- if .Values.enabled  }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "db-mariadb.fullname" . }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}

  {{- if ne (int .Values.port) 3306 }}
  port: {{ .Values.port }}
  {{- end }}

  rootPasswordSecretKeyRef:
    name: {{ include "db-mariadb.fullname" . }}-root
    key: password

  args:
    - "--character-set-filesystem=utf8"
    - "--lower-case-table-names=1"

  storage:
{{ toYaml .Values.storage | indent 4 }}

  service:
    type: LoadBalancer
{{- end }}