enabled: false

image:
  repository: mailhog/mailhog
  tag: latest
  pullPolicy: IfNotPresent

service:
  webPort: 8025
  smtpPort: 1025

ingress:
  enabled: false
  className: nginx
  host: mailhog.localhost
